name: qaniteen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animations: ^2.0.11
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  retrofit: ^4.1.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  feedback: ^3.1.0
  screenshot: ^3.0.0
  connectivity_plus: ^6.0.3
  logger: ^2.3.0
  flutter_animate: ^4.5.0
  google_sign_in: ^6.2.1
  easy_localization: ^3.0.7
  bloc: ^8.1.4
  pdf: ^3.10.8
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  flutter_inappwebview: ^6.0.0
  showcaseview: ^3.0.0
  upgrader: ^10.3.0
  in_app_review: ^2.0.9
  timeline_tile: ^2.0.0
  timelines: ^0.1.0
  timeago: ^3.6.1
  flutter_dotenv: ^5.1.0
  printing: ^5.12.0
  flutter_blurhash: ^0.8.2
  simple_animations: ^5.0.2
  webview_flutter: ^4.8.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  shimmer: ^3.0.0
  path_provider: ^2.1.3
  image_cropper: ^7.0.4
  in_app_purchase: ^3.2.0
  flutter_staggered_animations: ^1.1.1
  change_app_package_name: ^1.2.0
  path: ^1.9.0
  awesome_notifications: ^0.9.3+1
  modal_bottom_sheet: ^3.0.0
  auto_route: ^8.2.0
  flutter_facebook_auth: ^7.0.0
  grouped_list: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
