name: qaniteen
description: "A prayer application"
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Bloc
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  # Networking
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  # Fonts
  google_fonts: ^6.2.1
  # Flutter Utils
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  change_app_package_name: ^1.2.0
  # Notification
  flutter_local_notifications: ^17.1.2
  awesome_notifications: ^0.9.3+1
  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  # Image
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  # Location
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  # Json
  json_annotation: ^4.9.0
  # Urls
  url_launcher: ^6.3.0
  # Firebase
  firebase_core: ^3.1.0
  # Routing
  auto_route: ^8.2.0
  # Others
  intl: ^0.19.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  auto_route_generator: ^8.0.0



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/launcher_icon/
    - assets/splash/
