
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :distribute do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    
    firebase_app_distribution(
      app: "1:737022106780:android:7838094ff7a6d389846159",
      firebase_cli_token: "1//03sr8Hm3Aj4vOCgYIARAAGAMSNwF-L9IrPknliHwLsJclGuwW5X6wwj3xH0r4hv1ygP1n6_jWeo9fhY26Ky28KPq3W4U9yvYjXxA",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohamed.mahmoud02@eng-st.cu.edu.eg",
      release_notes: "This release includes the latest features and bug fixes."
    )
  end
end
